# Generated by Django 3.2.25 on 2026-08-24 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archerysettings', '0003_add_email_smtp_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaildb',
            options={'verbose_name': 'Email Setting', 'verbose_name_plural': 'Email Settings'},
        ),
    ]
