# Generated by Django 3.2.25 on 2026-08-31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archerysettings', '0004_alter_emaildb_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NmapSettingDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_id', models.UUIDField(blank=True, null=True)),
                ('binary_path', models.TextField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now=True, blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.organization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nmap_setting_db_created', to='user_management.userprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nmap_setting_db_updated', to='user_management.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='NiktoSettingDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_id', models.UUIDField(blank=True, null=True)),
                ('binary_path', models.TextField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now=True, blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.organization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nikto_setting_db_created', to='user_management.userprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nikto_setting_db_updated', to='user_management.userprofile')),
            ],
        ),
    ]