# Generated by Django 3.2.25 on 2026-08-31 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archerysettings', '0005_nmap_nikto_connector_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapsettingsdb',
            name='auth_method',
            field=models.CharField(choices=[('none', 'No Authentication'), ('formBased', 'Form-Based Login')], default='none', help_text='Authentication method for ZAP to use during scanning', max_length=20),
        ),
        migrations.AddField(
            model_name='zapsettingsdb',
            name='logged_in_regex',
            field=models.TextField(blank=True, default='', help_text='Regex that matches a page shown ONLY when logged in (e.g. Dashboard)'),
        ),
        migrations.AddField(
            model_name='zapsettingsdb',
            name='login_url',
            field=models.TextField(blank=True, default='', help_text='Full URL of the login form (e.g. http://target/login)'),
        ),
        migrations.AddField(
            model_name='zapsettingsdb',
            name='password_field',
            field=models.TextField(blank=True, default='password', help_text='HTML name attribute of the password input field'),
        ),
        migrations.AddField(
            model_name='zapsettingsdb',
            name='password_value',
            field=models.TextField(blank=True, default='', help_text='Password value to submit'),
        ),
        migrations.AddField(
            model_name='zapsettingsdb',
            name='username_field',
            field=models.TextField(blank=True, default='username', help_text='HTML name attribute of the username input field'),
        ),
        migrations.AddField(
            model_name='zapsettingsdb',
            name='username_value',
            field=models.TextField(blank=True, default='', help_text='Username / login value to submit'),
        ),
        migrations.AlterField(
            model_name='niktosettingdb',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nikto_setting_db_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='niktosettingdb',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nikto_setting_db_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nmapsettingdb',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nmap_setting_db_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nmapsettingdb',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nmap_setting_db_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
