"""
ZAP Scanner Adapter
Integrates existing zap_plugin.ZAPScanner with unified architecture
"""
from typing import Dict, Any, List, Optional
import logging
import uuid
from datetime import datetime

from scanners.base import (
    ScanConfig, ScanResult, ScanStatus, ScanType, 
    SeverityLevel, VulnerabilityResult
)
from scanners.adapters.abstracts import BaseScannerAdapter


logger = logging.getLogger(__name__)


class ZAPScannerAdapter(BaseScannerAdapter):
    """Adapter for existing ZAP scanner plugin"""

    @property
    def legacy_scanner_class(self):
        from webscanners.zapscanner import zap_plugin
        return zap_plugin.ZAPScanner

    @property
    def legacy_parser_class(self):
        from webscanners.zapscanner import zap_plugin
        return zap_plugin.ZAPScanner

    def initialize(self) -> bool:
        """Initialize ZAP scanner with existing configuration"""
        try:
            # Load ZAP settings from database
            from archerysettings.models import ZapSettingsDb
            zap_settings = ZapSettingsDb.objects.first()
            
            if not zap_settings:
                logger.error("ZAP settings not configured in database")
                return False
            
            self._zap_host = zap_settings.zap_host or "0.0.0.0"
            self._zap_port = zap_settings.zap_port or "8090"
            self._zap_api_key = zap_settings.zap_api_key or "dwed23wdwedwwefw4rwrfw"
            
            # Initialize legacy scanner
            self._legacy_scanner = self.legacy_scanner_class(
                target_url=self.config.target,
                project_id=self.config.project_id,
                rescan_id=None,
                rescan=None,
                random_port=self._zap_port,
                request=None
            )
            
            # Store scan config for parser
            self._scan_config = {
                'target': self.config.target,
                'project_id': self.config.project_id,
                'organization_id': self.config.organization_id,
                'created_by_id': self.config.created_by_id,
            }
            
            logger.info(f"ZAP adapter initialized for {self.config.target}")
            return True
        except Exception as e:
            logger.exception(f"ZAP initialization failed: {e}")
            return False

    def execute_scan(self) -> ScanResult:
        """Execute ZAP scan using existing plugin"""
        if not self._legacy_scanner:
            self.result.scan_status = ScanStatus.FAILED
            self.result.failure_reason = "Scanner not initialized"
            return self.result
        
        try:
            self.result.scan_status = ScanStatus.RUNNING
            self.result.started_at = datetime.now()
            
            # Run spider first
            spider_result = self._legacy_scanner.zap_spider()
            if spider_result is False:
                raise RuntimeError("ZAP spider failed")
            
            # Run active scan
            scan_result = self._legacy_scanner.zap_scan()
            if scan_result is False:
                raise RuntimeError("ZAP active scan failed")
            
            self.result.scan_status = ScanStatus.COMPLETED
            self.result.completed_at = datetime.now()
            
            # Get results
            vulns = self.get_results()
            self.result.total_vulns = len(vulns)
            
            for vuln in vulns:
                severity = vuln.get('severity', SeverityLevel.INFO)
                if isinstance(severity, SeverityLevel):
                    self.result.severity_counts[severity] = \
                        self.result.severity_counts.get(severity, 0) + 1
            
            logger.info(f"ZAP scan completed: {self.result.total_vulns} vulnerabilities found")
            return self.result
            
        except Exception as e:
            logger.exception(f"ZAP scan failed: {e}")
            self.result.scan_status = ScanStatus.FAILED
            self.result.failure_reason = str(e)
            self.result.completed_at = datetime.now()
            return self.result

    def get_results(self) -> List[Dict[str, Any]]:
        """Get scan results using existing XML parser"""
        if not self._legacy_scanner:
            return []
        
        try:
            # The existing ZAPScanner has methods to get results
            # Parse the XML report generated by ZAP
            from scanners.scanner_parser.web_scanner import zap_xml_parser
            import os
            
            # Look for ZAP XML report
            report_dir = os.path.join(os.getcwd(), "xml_reports")
            if not os.path.exists(report_dir):
                return []
            
            # Find the latest report for this target
            import glob
            target_safe = self.config.target.replace("://", "_").replace("/", "_").replace(":", "_")
            report_files = glob.glob(os.path.join(report_dir, f"*{target_safe}*.xml"))
            
            if not report_files:
                return []
            
            latest_report = max(report_files, key=os.path.getctime)
            
            # Use existing parser
            with open(latest_report, 'r') as f:
                content = f.read()
            
            # Parse using existing parser
            from django.http import HttpRequest
            request = HttpRequest()
            request.META = {}
            request.user = None
            
            # The existing parser expects a file-like object
            import io
            file_obj = io.StringIO(content)
            parsed_results = zap_xml_parser.xml_parser(request, file_obj, 
                                                        project_id=self.config.project_id,
                                                        scan_id=self.config.scan_id,
                                                        username=None)
            
            return parsed_results if parsed_results else []
            
        except Exception as e:
            logger.exception(f"Failed to get ZAP results: {e}")
            return []

    def cleanup(self) -> bool:
        """Cleanup ZAP resources"""
        try:
            if self._legacy_scanner and hasattr(self._legacy_scanner, 'zap_shutdown'):
                self._legacy_scanner.zap_shutdown()
            return True
        except Exception as e:
            logger.error(f"ZAP cleanup failed: {e}")
            return False