# Generated by Django 3.2.25 on 2025-10-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webscanners", "0029_auto_20230506_1302"),
    ]

    operations = [
        migrations.AddField(
            model_name="webscansdb",
            name="failure_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]

