# Generated by Django 3.2.25 on 2025-10-07

from django.db import migrations


def backfill_failure_reason(apps, schema_editor):
    WebScansDb = apps.get_model('webscanners', 'WebScansDb')
    for row in WebScansDb.objects.all().iterator():
        # Normalize values to integers where possible
        def nz(v):
            if v is None:
                return 0
            try:
                return int(str(v).strip() or 0)
            except Exception:
                return 0

        totals = [
            nz(row.total_vul),
            nz(row.critical_vul),
            nz(row.high_vul),
            nz(row.medium_vul),
            nz(row.low_vul),
            nz(row.info_vul),
            nz(row.total_dup),
        ]
        if sum(totals) == 0 and (row.failure_reason is None or str(row.failure_reason).strip() == ""):
            row.failure_reason = "Scan appears failed: empty results (no vulnerabilities or duplicates recorded)."
            row.save(update_fields=["failure_reason"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("webscanners", "0030_webscansdb_failure_reason"),
    ]

    operations = [
        migrations.RunPython(backfill_failure_reason, noop),
    ]

