# Generated by Django 3.2.25 on 2026-08-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscanners', '0037_task_schedule_scan_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webscansdb',
            name='reated_time',
        ),
        migrations.AddField(
            model_name='webscanresultsdb',
            name='cvss_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webscanresultsdb',
            name='mitre_techniques',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webscanresultsdb',
            name='risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
