# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

"""
Django settings for archerysecurity project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

from django.contrib.messages import constants as messages

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".."
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = os.environ.get("DJANGO_DEBUG") == "1"
# DEBUG = True

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "SET ME")

ALLOWED_HOSTS = ["*"]

AUTHENTICATION_BACKENDS = [
    "authentication.backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Application definition

INSTALLED_APPS = [
    "archerysecurity",
    "rest_framework",
    "webscanners",
    "projects",
    "archerysettings",
    "archeryapi",
    "networkscanners",
    "staticscanners",
    "cloudscanners",
    "jiraticketing",
    "cicd",
    "tools",
    "pentest",
    "report_upload",
    "scheduler.apps.SchedulerConfig",
    "django.contrib.admin",
    "stronghold",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework.authtoken",
    "debug_toolbar",
    "dashboard",
    "sitetree",
    "import_export",
    "compliance",
    "notifications",
    "user_management",
    "authentication",
    "rest_framework_simplejwt.token_blacklist",
    "reports",
    "scanners",
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "stronghold.middleware.LoginRequiredMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "archerysecurity.middleware.NoCacheMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = "archerysecurity.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django_settings_export.settings_export",
                "scanners.scanner_parser.scanner_parser.parser_dict",
            ],
        },
    },
]

MESSAGE_STORAGE = "django.contrib.messages.storage.cookie.CookieStorage"

WSGI_APPLICATION = "archerysecurity.wsgi.application"

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LANGUAGE_CODE = "en-us"

# Default application time zone. Override with env TIME_ZONE if needed.
# Set to Malaysia time by default.
DEF_TIME_ZONE = "Asia/Kuala_Lumpur"

# Keep naive datetimes in base to avoid legacy code aware/naive conflicts; production overrides to True.
USE_TZ = False

TIME_ZONE = os.getenv("TIME_ZONE", DEF_TIME_ZONE)

USE_I18N = True

USE_L10N = True

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")

AUTH_USER_MODEL = "user_management.UserProfile"

MESSAGE_TAGS = {
    messages.DEBUG: "alert-info",
    messages.INFO: "alert-info",
    messages.SUCCESS: "alert-success",
    messages.WARNING: "alert-warning",
    messages.ERROR: "alert-danger",
}

STRONGHOLD_PUBLIC_URLS = (
    r"^/admin.*?$",  # Don't touch the admin pages
    r"^/accounts/login/$",  # Avoid redirect loop
    r"^/api.*?$",
    r"^/api/v1/activate/$",
    r"^/api/v1/forget-user-password/$",
    r"^/o.*?$",
    r"^/auth/login/$",  # Allow login page
    r"^/auth/$",  # Allow auth endpoint
    r"^/logout/$",  # Allow logout
)

LOGIN_URL = "/auth/login/"

LOGIN_REDIRECT_URL = "/user/accounts/"

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema",
}

# Nikto defaults (exported to templates)
import os as _os
NIKTO_DEFAULT_DISABLE_FAILURES = (_os.getenv("NIKTO_DEFAULT_DISABLE_FAILURES", "False").lower() == "true")
NIKTO_DEFAULT_USER_AGENT = _os.getenv("NIKTO_DEFAULT_USER_AGENT", "")
try:
    NIKTO_DEFAULT_FAILURES = int(_os.getenv("NIKTO_DEFAULT_FAILURES", "0"))
except Exception:
    NIKTO_DEFAULT_FAILURES = 0

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# SESSION_COOKIE_AGE = 5 * 100

REFRESH_TIMER = 5
SCAN_POLL_INTERVAL = int(os.getenv("SCAN_POLL_INTERVAL", "2"))

SETTINGS_EXPORT = [
    "REFRESH_TIMER",
    "SCAN_POLL_INTERVAL",
    "NIKTO_DEFAULT_DISABLE_FAILURES",
    "NIKTO_DEFAULT_USER_AGENT",
    "NIKTO_DEFAULT_FAILURES",
]

DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800

try:
    from archerysecurity.local_settings import *
except ImportError:
    pass

IMPORT_EXPORT_USE_TRANSACTIONS = True

# DJANGO_NOTIFICATIONS_CONFIG = {'USE_JSONFIELD': True}

DJANGO_NOTIFICATIONS_CONFIG = {"SOFT_DELETE": True}

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Nikto directories (configurable via env). Default to project paths used in Docker.
# If the paths are not writable, attempt to fall back to a temp directory.
_NIKTO_RESULT_DIR_DEFAULT = os.path.join(BASE_DIR, "nikto_result")
_NIKTO_LOG_DIR_DEFAULT = os.path.join(BASE_DIR, "logs", "nikto")

NIKTO_RESULT_DIR = os.getenv("NIKTO_RESULT_DIR", _NIKTO_RESULT_DIR_DEFAULT)
NIKTO_LOG_DIR = os.getenv("NIKTO_LOG_DIR", _NIKTO_LOG_DIR_DEFAULT)
NIKTO_DIR_FALLBACK_USED = False
NIKTO_DIR_FALLBACK_REASON = ""

try:
    os.makedirs(NIKTO_RESULT_DIR, exist_ok=True)
    os.makedirs(NIKTO_LOG_DIR, exist_ok=True)
except Exception:
    # Fall back to temp directory if the configured/default directories are not writable
    try:
        import tempfile
        _tmp_base = os.path.join(tempfile.gettempdir(), "archerysec")
        _tmp_result = os.path.join(_tmp_base, "nikto_result")
        _tmp_logs = os.path.join(_tmp_base, "logs", "nikto")
        os.makedirs(_tmp_result, exist_ok=True)
        os.makedirs(_tmp_logs, exist_ok=True)
        NIKTO_RESULT_DIR = _tmp_result
        NIKTO_LOG_DIR = _tmp_logs
        NIKTO_DIR_FALLBACK_USED = True
        NIKTO_DIR_FALLBACK_REASON = "Configured directories not writable; using temp folders"
    except Exception:
        # As a last resort, keep the original values; the app may show errors when writing
        pass

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

CORS_ALLOW_ALL_ORIGINS = True  # Allow requests from all origins (not recommended for production)
CORS_ALLOW_CREDENTIALS = True  # Allow credentials (e.g., cookies) to be sent with CORS requests

CORS_ALLOWED_ORIGINS = [
    'http://localhost:4200',  # Add your Angular application's URL
    # Other allowed origins...
]

CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']  # Allowed HTTP methods
CORS_ALLOW_HEADERS = ['Authorization', 'Content-Type']  # Allowed request headers
CORS_EXPOSE_HEADERS = ['Content-Disposition']  # Headers exposed to the client

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(levelname)s:%(name)s: %(message)s "
            "(%(asctime)s; %(filename)s:%(lineno)d)",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        }
    },
    "filters": {
        "sourcemap_404": {"()": "archerysecurity.logfilters.IgnoreSourceMap404"},
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "formatter": "standard",
            "class": "logging.StreamHandler",
            "filters": ["sourcemap_404"],
        },
        "rotate_file": {
            "level": "INFO",
            "formatter": "standard",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "server.log",
            "encoding": "utf8",
            "maxBytes": 100000,
            "backupCount": 1,
            "filters": ["sourcemap_404"],
        },
    },
    "loggers": {
        "": {"handlers": ["console", "rotate_file"], "level": "INFO"},
        "pdfminer": {"level": "CRITICAL"},
    },
}
