# Generated by Django 3.2.25 on 2026-06-27 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0019_auto_20230506_1302'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0004_userprofile_created_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedScanSummary',
            fields=[
                ('scan_id', models.UUIDField(primary_key=True, serialize=False)),
                ('scan_type', models.CharField(choices=[('web', 'Web Application'), ('network', 'Network'), ('static', 'Static Code Analysis'), ('cloud', 'Cloud Infrastructure'), ('compliance', 'Compliance'), ('container', 'Container'), ('sast', 'SAST'), ('dast', 'DAST')], max_length=20)),
                ('scanner_name', models.CharField(max_length=50)),
                ('target', models.TextField()),
                ('total_vulns', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
                ('unknown_count', models.IntegerField(default=0)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectdb')),
            ],
            options={
                'db_table': 'unified_scan_summary',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnifiedScanResult',
            fields=[
                ('scan_id', models.UUIDField(default=uuid.uuid4)),
                ('result_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('scan_type', models.CharField(choices=[('web', 'Web Application'), ('network', 'Network'), ('static', 'Static Code Analysis'), ('cloud', 'Cloud Infrastructure'), ('compliance', 'Compliance'), ('container', 'Container'), ('sast', 'SAST'), ('dast', 'DAST')], max_length=20)),
                ('scanner_name', models.CharField(max_length=50)),
                ('target', models.TextField()),
                ('vulnerability', models.JSONField(default=dict)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational'), ('unknown', 'Unknown')], default='info', max_length=20)),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('cvss_vector', models.CharField(blank=True, max_length=100)),
                ('cwe_id', models.CharField(blank=True, max_length=20)),
                ('cve_id', models.CharField(blank=True, max_length=20)),
                ('url', models.TextField(blank=True)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.CharField(blank=True, max_length=10)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('parameter', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('evidence', models.TextField(blank=True)),
                ('request', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('payload', models.TextField(blank=True)),
                ('dup_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('false_positive', models.BooleanField(default=False)),
                ('duplicate', models.BooleanField(default=False)),
                ('vuln_status', models.CharField(choices=[('open', 'Open'), ('fixed', 'Fixed'), ('false_positive', 'False Positive'), ('risk_accepted', 'Risk Accepted'), ('in_progress', 'In Progress')], default='open', max_length=20)),
                ('references', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectdb')),
            ],
            options={
                'db_table': 'unified_scan_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnifiedScanConfig',
            fields=[
                ('scan_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('scan_type', models.CharField(choices=[('web', 'Web Application'), ('network', 'Network'), ('static', 'Static Code Analysis'), ('cloud', 'Cloud Infrastructure'), ('compliance', 'Compliance'), ('container', 'Container'), ('sast', 'SAST'), ('dast', 'DAST')], max_length=20)),
                ('scanner_name', models.CharField(max_length=50)),
                ('target', models.TextField()),
                ('targets', models.JSONField(blank=True, default=list)),
                ('profile', models.CharField(blank=True, max_length=50, null=True)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('timeout', models.IntegerField(default=3600)),
                ('schedule_config', models.JSONField(blank=True, null=True)),
                ('schedule_type', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectdb')),
            ],
            options={
                'db_table': 'unified_scan_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='unifiedscansummary',
            index=models.Index(fields=['scan_type', 'organization'], name='unified_sca_scan_ty_0affd8_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedscansummary',
            index=models.Index(fields=['scan_status', 'organization'], name='unified_sca_scan_st_d1f776_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedscanresult',
            index=models.Index(fields=['scan_id', 'scan_type'], name='unified_sca_scan_id_0c36e3_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedscanresult',
            index=models.Index(fields=['scan_type', 'organization'], name='unified_sca_scan_ty_a4c5cc_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedscanresult',
            index=models.Index(fields=['scanner_name', 'organization'], name='unified_sca_scanner_d0e0c7_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedscanresult',
            index=models.Index(fields=['severity', 'organization'], name='unified_sca_severit_8b3a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedscanresult',
            index=models.Index(fields=['dup_hash', 'organization'], name='unified_sca_dup_has_20b455_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedscanresult',
            index=models.Index(fields=['vuln_status', 'organization'], name='unified_sca_vuln_st_0e1c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedscanresult',
            index=models.Index(fields=['created_at'], name='unified_sca_created_768ee0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unifiedscanresult',
            unique_together={('scan_id', 'result_id')},
        ),
        migrations.AddIndex(
            model_name='unifiedscanconfig',
            index=models.Index(fields=['scan_type', 'organization'], name='unified_sca_scan_ty_687ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedscanconfig',
            index=models.Index(fields=['scanner_name', 'organization'], name='unified_sca_scanner_ed0dcd_idx'),
        ),
    ]
