# Generated by Django 3.2.25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NvdCache',
            fields=[
                ('cve_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('cvss_severity', models.CharField(blank=True, max_length=20, null=True)),
                ('cvss_vector', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('references', models.JSONField(blank=True, default=list, null=True)),
                ('source', models.CharField(default='nvd', max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NVD Cache Entry',
                'verbose_name_plural': 'NVD Cache Entries',
                'db_table': 'nvd_cache',
            },
        ),
    ]
